bgm_volume: 0.3
enable_bgm: false
enable_cover: true
enable_subtitle: true
heygem_ifface: true
heygem_steps: 8
max_workers: 3
subtitle_color: white
subtitle_font: SimHei
subtitle_position: bottom
subtitle_size: 24
tts_denoise_strength: 0.7
tts_emo_weight: 0.8
tts_enable_denoise: false
tts_speed: 1
